# Generated by Django 3.2.8 on 2021-11-01 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesdb.user'),
        ),
    ]
