# Generated by Django 3.2.8 on 2021-11-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesdb', '0002_alter_message_message_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_author',
        ),
        migrations.AddField(
            model_name='message',
            name='message_author_id',
            field=models.IntegerField(default=1, verbose_name='id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='unread',
            field=models.ManyToManyField(to='mesdb.User'),
        ),
    ]
