# Generated by Django 3.2.8 on 2022-01-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesdb', '0003_auto_20211106_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_time',
            field=models.IntegerField(default=1643273397.9323454),
        ),
    ]
