# Generated by Django 3.2.8 on 2022-10-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesdb', '0005_auto_20220127_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(verbose_name='Номер дня в учебном году')),
                ('class_array', models.TextField(verbose_name='Массив уроков')),
                ('task_array', models.TextField(verbose_name='Массив заданий')),
                ('description_array', models.TextField(verbose_name='Массив пояснений')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.IntegerField(default=1666008226.7347283),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(default='../../static/img/def.jpg', upload_to='avatars/'),
        ),
    ]
