# Generated by Django 3.2.8 on 2022-10-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesdb', '0006_auto_20221017_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашние задания'},
        ),
        migrations.AddField(
            model_name='user',
            name='class_letter',
            field=models.CharField(default='G', max_length=1, verbose_name='Буква класса'),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.IntegerField(default=-1, verbose_name='Параллель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.IntegerField(default=1666357390.1918266),
        ),
    ]
