# Generated by Django 3.2.8 on 2022-10-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesdb', '0007_auto_20221021_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_class',
            field=models.BooleanField(default=False, verbose_name='Это класс?'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.IntegerField(default=1666360194.1155195),
        ),
    ]
