# Generated by Django 3.2.8 on 2022-10-29 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesdb', '0008_auto_20221021_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='homework_chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mesdb.chat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.IntegerField(default=1667028074.9575925),
        ),
    ]
