# Generated by Django 3.2.8 on 2022-11-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesdb', '0010_auto_20221031_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_it_bot',
            field=models.BooleanField(default=False, verbose_name='Это BOT'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='class_1',
            field=models.CharField(default='Физика', max_length=20, verbose_name='1 урок'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='class_2',
            field=models.CharField(default='Физика', max_length=20, verbose_name='2 урок'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='class_3',
            field=models.CharField(default='Физика', max_length=20, verbose_name='3 урок'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='class_4',
            field=models.CharField(default='Физика', max_length=20, verbose_name='4 урок'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='class_5',
            field=models.CharField(default='Физика', max_length=20, verbose_name='5 урок'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='class_6',
            field=models.CharField(default='Физика', max_length=20, verbose_name='6 урок'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='class_7',
            field=models.CharField(default='Физика', max_length=20, verbose_name='7 урок'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='class_8',
            field=models.CharField(default='Физика', max_length=20, verbose_name='8 урок'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description_1',
            field=models.TextField(default='Физика', verbose_name='Пояснение к уроку 1'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description_2',
            field=models.TextField(default='Физика', verbose_name='Пояснение к уроку 2'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description_3',
            field=models.TextField(default='Физика', verbose_name='Пояснение к уроку 3'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description_4',
            field=models.TextField(default='Физика', verbose_name='Пояснение к уроку 4'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description_5',
            field=models.TextField(default='Физика', verbose_name='Пояснение к уроку 5'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description_6',
            field=models.TextField(default='Физика', verbose_name='Пояснение к уроку 6'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description_7',
            field=models.TextField(default='Физика', verbose_name='Пояснение к уроку 7'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description_8',
            field=models.TextField(default='Физика', verbose_name='Пояснение к уроку 8'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='task_1',
            field=models.TextField(default='Физика', verbose_name='задание на 1 урок'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='task_2',
            field=models.TextField(default='Физика', verbose_name='задание на 1 урок'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='task_3',
            field=models.TextField(default='Физика', verbose_name='задание на 1 урок'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='task_4',
            field=models.TextField(default='Физика', verbose_name='задание на 1 урок'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='task_5',
            field=models.TextField(default='Физика', verbose_name='задание на 1 урок'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='task_6',
            field=models.TextField(default='Физика', verbose_name='задание на 1 урок'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='task_7',
            field=models.TextField(default='Физика', verbose_name='задание на 1 урок'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='task_8',
            field=models.TextField(default='Физика', verbose_name='задание на 1 урок'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.IntegerField(default=1668097844.4903467),
        ),
    ]
