# Generated by Django 3.2.8 on 2022-11-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesdb', '0011_auto_20221110_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.IntegerField(default=1668097888.2543702),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_it_bot',
            field=models.BooleanField(default=False, verbose_name='Это BOT?'),
        ),
    ]
